codefresh:
- codefresh/**
- codefresh.yml

docker:
- Dockerfile
- apk/Dockerfile.*

docs:
- docs/**

github:
- .github/**

scripts:
- bin/**
- tasks/**
vendor: vendor/**
vendor/amtool: vendor/amtool/**
vendor/assume-role: vendor/assume-role/**
vendor/atlantis: vendor/atlantis/**
vendor/awless: vendor/awless/**
vendor/aws-iam-authenticator: vendor/aws-iam-authenticator/**
vendor/aws-okta: vendor/aws-okta/**
vendor/aws-vault: vendor/aws-vault/**
vendor/cfssl: vendor/cfssl/**
vendor/chamber: vendor/chamber/**
vendor/cli53: vendor/cli53/**
vendor/cloudflared: vendor/cloudflared/**
vendor/cloudposse-atlantis: vendor/cloudposse-atlantis/**
vendor/codefresh: vendor/codefresh/**
vendor/ctop: vendor/ctop/**
vendor/direnv: vendor/direnv/**
vendor/doctl: vendor/doctl/**
vendor/duffle: vendor/duffle/**
vendor/emailcli: vendor/emailcli/**
vendor/fargate: vendor/fargate/**
vendor/fetch: vendor/fetch/**
vendor/figurine: vendor/figurine/**
vendor/fzf: vendor/fzf/**
vendor/ghr: vendor/ghr/**
vendor/github-commenter: vendor/github-commenter/**
vendor/github-release: vendor/github-release/**
vendor/github-status-updater: vendor/github-status-updater/**
vendor/gitleaks: vendor/gitleaks/**
vendor/gomplate: vendor/gomplate/**
vendor/goofys: vendor/goofys/**
vendor/gosu: vendor/gosu/**
vendor/gotop: vendor/gotop/**
vendor/helm: vendor/helm/**
vendor/helmfile: vendor/helmfile/**
vendor/htmltest: vendor/htmltest/**
vendor/hugo: vendor/hugo/**
vendor/json2hcl: vendor/json2hcl/**
vendor/jx: vendor/jx/**
vendor/k3d: vendor/k3d/**
vendor/k6: vendor/k6/**
vendor/k9s: vendor/k9s/**
vendor/katafygio: vendor/katafygio/**
vendor/kfctl: vendor/kfctl/**
vendor/kind: vendor/kind/**
vendor/kops-1.12: vendor/kops-1.12/**
vendor/kops: vendor/kops/**
vendor/krew: vendor/krew/**
vendor/kubecron: vendor/kubecron/**
vendor/kubectl-1.13: vendor/kubectl-1.13/**
vendor/kubectl-1.14: vendor/kubectl-1.14/**
vendor/kubectl: vendor/kubectl/**
vendor/kubectx: vendor/kubectx/**
vendor/kubens: vendor/kubens/**
vendor/lazydocker: vendor/lazydocker/**
vendor/lectl: vendor/lectl/**
vendor/misspell: vendor/misspell/**
vendor/packer: vendor/packer/**
vendor/pandoc: vendor/pandoc/**
vendor/pgmetrics: vendor/pgmetrics/**
vendor/popeye: vendor/popeye/**
vendor/promtool: vendor/promtool/**
vendor/rakkess: vendor/rakkess/**
vendor/rancher: vendor/rancher/**
vendor/rbac-lookup: vendor/rbac-lookup/**
vendor/retry: vendor/retry/**
vendor/scenery: vendor/scenery/**
vendor/sentry-cli: vendor/sentry-cli/**
vendor/shellcheck: vendor/shellcheck/**
vendor/shfmt: vendor/shfmt/**
vendor/slack-notifier: vendor/slack-notifier/**
vendor/sops: vendor/sops/**
vendor/stern: vendor/stern/**
vendor/sudosh: vendor/sudosh/**
vendor/teleport: vendor/teleport/**
vendor/terraform-0.11: vendor/terraform-0.11/**
vendor/terraform-0.12: vendor/terraform-0.12/**
vendor/terraform-docs: vendor/terraform-docs/**
vendor/terraform: vendor/terraform/**
vendor/terragrunt: vendor/terragrunt/**
vendor/terrahelp: vendor/terrahelp/**
vendor/tfenv: vendor/tfenv/**
vendor/tfmask: vendor/tfmask/**
vendor/variant: vendor/variant/**
vendor/venona: vendor/venona/**
vendor/yq: vendor/yq/**
