codefresh:
- codefresh/**
- codefresh.yml

docker:
- Dockerfile
- "*/Dockerfile.*"

# Docs are updated on every PR, not a helpful label
#docs:
#- docs/**

github:
- .github/**

scripts:
- bin/**
- tasks/**

# suppress individual package labels when scripts change,
# because they affect all packages, we have more than 100 packages,
# and there is a limit of 100 labels on a PR.
vendor/amazon-ecr-credential-helper:
- any: ["vendor/amazon-ecr-credential-helper/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/amtool:
- any: ["vendor/amtool/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/argocd:
- any: ["vendor/argocd/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/assume-role:
- any: ["vendor/assume-role/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/atlantis:
- any: ["vendor/atlantis/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/atmos:
- any: ["vendor/atmos/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/awless:
- any: ["vendor/awless/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/aws-copilot-cli:
- any: ["vendor/aws-copilot-cli/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/aws-iam-authenticator:
- any: ["vendor/aws-iam-authenticator/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/aws-nuke:
- any: ["vendor/aws-nuke/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/aws-okta:
- any: ["vendor/aws-okta/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/aws-vault:
- any: ["vendor/aws-vault/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cfssl:
- any: ["vendor/cfssl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cfssljson:
- any: ["vendor/cfssljson/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/chamber:
- any: ["vendor/chamber/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cilium-cli:
- any: ["vendor/cilium-cli/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cli53:
- any: ["vendor/cli53/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cloud-nuke:
- any: ["vendor/cloud-nuke/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cloudflared:
- any: ["vendor/cloudflared/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/cloudposse-atlantis:
- any: ["vendor/cloudposse-atlantis/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/codefresh:
- any: ["vendor/codefresh/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/conftest:
- any: ["vendor/conftest/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/consul:
- any: ["vendor/consul/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/ctop:
- any: ["vendor/ctop/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/direnv:
- any: ["vendor/direnv/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/doctl:
- any: ["vendor/doctl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/duffle:
- any: ["vendor/duffle/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/ec2-instance-selector:
- any: ["vendor/ec2-instance-selector/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/ecspresso:
- any: ["vendor/ecspresso/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/emailcli:
- any: ["vendor/emailcli/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/envcli:
- any: ["vendor/envcli/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/fargate:
- any: ["vendor/fargate/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/fetch:
- any: ["vendor/fetch/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/figurine:
- any: ["vendor/figurine/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/fzf:
- any: ["vendor/fzf/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/gh:
- any: ["vendor/gh/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/ghr:
- any: ["vendor/ghr/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/github-commenter:
- any: ["vendor/github-commenter/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/github-release:
- any: ["vendor/github-release/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/github-status-updater:
- any: ["vendor/github-status-updater/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/gitleaks:
- any: ["vendor/gitleaks/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/go-jsonnet:
- any: ["vendor/go-jsonnet/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/gomplate:
- any: ["vendor/gomplate/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/gonsul:
- any: ["vendor/gonsul/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/goofys:
- any: ["vendor/goofys/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/gosu:
- any: ["vendor/gosu/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/gotop:
- any: ["vendor/gotop/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/grpcurl:
- any: ["vendor/grpcurl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/hcledit:
- any: ["vendor/hcledit/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/hcloud:
- any: ["vendor/hcloud/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/helm:
- any: ["vendor/helm/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/helm2:
- any: ["vendor/helm2/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/helm3:
- any: ["vendor/helm3/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/helmfile:
- any: ["vendor/helmfile/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/htmltest:
- any: ["vendor/htmltest/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/hugo:
- any: ["vendor/hugo/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/infracost:
- any: ["vendor/infracost/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/jp:
- any: ["vendor/jp/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/jq:
- any: ["vendor/jq/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/json2hcl:
- any: ["vendor/json2hcl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/jx:
- any: ["vendor/jx/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/k3d:
- any: ["vendor/k3d/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/k6:
- any: ["vendor/k6/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/k9s:
- any: ["vendor/k9s/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/katafygio:
- any: ["vendor/katafygio/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kfctl:
- any: ["vendor/kfctl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kind:
- any: ["vendor/kind/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kops-1.12:
- any: ["vendor/kops-1.12/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kops:
- any: ["vendor/kops/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/krew:
- any: ["vendor/krew/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubecron:
- any: ["vendor/kubecron/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.13:
- any: ["vendor/kubectl-1.13/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.14:
- any: ["vendor/kubectl-1.14/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.15:
- any: ["vendor/kubectl-1.15/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.16:
- any: ["vendor/kubectl-1.16/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.17:
- any: ["vendor/kubectl-1.17/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.18:
- any: ["vendor/kubectl-1.18/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.19:
- any: ["vendor/kubectl-1.19/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.20:
- any: ["vendor/kubectl-1.20/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.21:
- any: ["vendor/kubectl-1.21/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.22:
- any: ["vendor/kubectl-1.22/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.23:
- any: ["vendor/kubectl-1.23/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.24:
- any: ["vendor/kubectl-1.24/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.25:
- any: ["vendor/kubectl-1.25/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.26:
- any: ["vendor/kubectl-1.26/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.27:
- any: ["vendor/kubectl-1.27/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.28:
- any: ["vendor/kubectl-1.28/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.29:
- any: ["vendor/kubectl-1.29/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.30:
- any: ["vendor/kubectl-1.30/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl-1.31:
- any: ["vendor/kubectl-1.31/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectl:
- any: ["vendor/kubectl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubectx:
- any: ["vendor/kubectx/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubens:
- any: ["vendor/kubens/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/kubeval:
- any: ["vendor/kubeval/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/lazydocker:
- any: ["vendor/lazydocker/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/lectl:
- any: ["vendor/lectl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/minikube:
- any: ["vendor/minikube/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/misspell:
- any: ["vendor/misspell/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/nomad:
- any: ["vendor/nomad/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/opa:
- any: ["vendor/opa/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/pack:
- any: ["vendor/pack/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/packer:
- any: ["vendor/packer/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/pandoc:
- any: ["vendor/pandoc/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/pgmetrics:
- any: ["vendor/pgmetrics/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/pluto:
- any: ["vendor/pluto/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/popeye:
- any: ["vendor/popeye/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/promtool:
- any: ["vendor/promtool/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/rainbow-text:
- any: ["vendor/rainbow-text/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/rakkess:
- any: ["vendor/rakkess/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/rancher:
- any: ["vendor/rancher/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/rbac-lookup:
- any: ["vendor/rbac-lookup/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/retry:
- any: ["vendor/retry/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/saml2aws:
- any: ["vendor/saml2aws/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/scenery:
- any: ["vendor/scenery/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/sentinel:
- any: ["vendor/sentinel/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/sentry-cli:
- any: ["vendor/sentry-cli/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/shellcheck:
- any: ["vendor/shellcheck/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/shfmt:
- any: ["vendor/shfmt/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/slack-notifier:
- any: ["vendor/slack-notifier/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/sops:
- any: ["vendor/sops/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/spacectl:
- any: ["vendor/spacectl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/spotctl:
- any: ["vendor/spotctl/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/sshm:
- any: ["vendor/sshm/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/stern:
- any: ["vendor/stern/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/sudosh:
- any: ["vendor/sudosh/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/teleport-4.2:
- any: ["vendor/teleport-4.2/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/teleport-4.3:
- any: ["vendor/teleport-4.3/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/teleport-4.4:
- any: ["vendor/teleport-4.4/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/teleport-5.0:
- any: ["vendor/teleport-5.0/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/teleport:
- any: ["vendor/teleport/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-0.11:
- any: ["vendor/terraform-0.11/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-0.12:
- any: ["vendor/terraform-0.12/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-0.13:
- any: ["vendor/terraform-0.13/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-0.14:
- any: ["vendor/terraform-0.14/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-0.15:
- any: ["vendor/terraform-0.15/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-1:
- any: ["vendor/terraform-1/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-config-inspect:
- any: ["vendor/terraform-config-inspect/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-docs:
- any: ["vendor/terraform-docs/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform-module-versions:
- any: ["vendor/terraform-module-versions/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform:
- any: ["vendor/terraform/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform_0.11:
- any: ["vendor/terraform_0.11/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform_0.12:
- any: ["vendor/terraform_0.12/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terraform_0.13:
- any: ["vendor/terraform_0.13/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terragrunt:
- any: ["vendor/terragrunt/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/terrahelp:
- any: ["vendor/terrahelp/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/tfenv:
- any: ["vendor/tfenv/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/tflint:
- any: ["vendor/tflint/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/tfmask:
- any: ["vendor/tfmask/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/tfschema:
- any: ["vendor/tfschema/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/tfsec:
- any: ["vendor/tfsec/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/thanos:
- any: ["vendor/thanos/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/trivy:
- any: ["vendor/trivy/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/turf:
- any: ["vendor/turf/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/variant:
- any: ["vendor/variant/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/variant2:
- any: ["vendor/variant2/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/vault:
- any: ["vendor/vault/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/velero:
- any: ["vendor/velero/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/vendir:
- any: ["vendor/vendir/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/venona:
- any: ["vendor/venona/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/vert:
- any: ["vendor/vert/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/yajsv:
- any: ["vendor/yajsv/**"]
  all: ["!bin/**", "!tasks/**"]
vendor/yq:
- any: ["vendor/yq/**"]
  all: ["!bin/**", "!tasks/**"]
