FROM centos:centos8

ENV LC_ALL=C.UTF-8

RUN yum clean all && yum -y install ruby-devel gcc make rpm-build rubygems git zip bzip2 jq
RUN gem install --no-document fpm
# https://github.com/jordansissel/fpm/issues/1663
RUN gem uninstall --all --ignore-dependencies --force backports
RUN gem install --no-document backports -v 3.15.0
WORKDIR /packages
