# APK
export PACKAGER_PRIVKEY=$(CURDIR)/key.rsa
export APK_TEMPLATE_PATH ?= templates/
export APK_BUILD_TEMPLATE ?= APKBUILD.github-binary


apk/prepare: 
	cp -a ${APK_TEMPLATE_PATH}/${APK_BUILD_TEMPLATE} APKBUILD
	chmod 777 /var/cache/distfiles

apk/checksum:
	sudo -E -u nobody abuild checksum

apk/build:
	addgroup nobody abuild
	sudo -E -u nobody abuild -c -r -P /tmp/packages

apk/clean:
	rm -f APKBUILD /tmp/packages/x86_64/APKINDEX.tar.gz


apk: apk/prepare apk/checksum apk/build apk/clean

