# Need to use version number so that it gets updated here and triggers a build
FROM alpine:3.20.3

ENV LC_ALL=C.UTF-8
ENV PS1="(apk) \w \$ "

# install the cloudposse alpine repository
RUN apk add --no-cache bash curl && \
  curl -1sLf \
  'https://dl.cloudsmith.io/public/cloudposse/packages/setup.alpine.sh' \
  | bash && \
  printf "@cloudposse %s\n\n" "$(grep -h -v '^[@#]' /etc/apk/repositories | grep -F "public/cloudposse/packages" | head -1)" \
  >> /etc/apk/repositories

# Install and tag the @testing repo
RUN echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk update && \
    apk add make curl alpine-sdk shadow bash jq sudo go  && \
    apk add --update -U python3 python3-dev py3-pip libffi-dev gcc linux-headers musl-dev openssl-dev

RUN echo "auth       sufficient   pam_shells.so" > /etc/pam.d/chsh
