FROM debian:stable-slim

ENV LC_ALL=C.UTF-8
ENV PS1="(deb) \w \$ "

RUN apt-get update && \
    apt-get -y install bash ruby ruby-dev rubygems build-essential curl git zip bzip2 jq
# https://github.com/jordansissel/fpm/issues/1663
RUN gem install --no-document backports -v 3.15.0
RUN gem install --no-document fpm

WORKDIR /packages
